# Generated by Django 3.0.7 on 2020-07-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
