# Generated by Django 3.0.7 on 2020-07-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_auto_20200720_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
